### ISSUE TITLE
empty data from user browser session

### ISSUE THREAD

**Issue by nalui333** [jupyterhub/kerberosauthenticator#4]
HI, seems i can't get this to pull down user data with which to authenticate against a kerberos realm with.

I get unknown user and placing debug statements show data coming into the authenticate module as none. 

Is there some additional functionality that needs to be written to make this work with jupyterhub? Thanks

**Comment by jcrist** [comment]
Is your browser configured to allow SPNEGO authentication at the domain you're serving JupyterHub at? https://jcrist.github.io/kerberosauthenticator/#enabling-kerberos-authentication-in-your-browser

**Comment by nalui333** [comment]
yes in firefox i have all the kerberos configuration setup with the domains to authenticate against as well as the hostname of the jupyterhub server

one thing i notice is that i only get a sign in with kerberos button on the main page after enabling this module and thereafter i don't get a prompt to put in my username or any other data, i assume this means it pulls that from the browser somehow, or is this not the expected behaviour

**Comment by jcrist** [comment]
Yes. SPNEGO authentication is automatic and doesn't require user input.

A few other potential issues related to your setup:
- your browser doesn't know where your ticket cache is, or doesn't have access to it. This is set by the `krb5.conf` file/`KRB5_CONFIG` environment variable.
- your browser doesn't know where the kerberos daemon is running. Also solved by appropriately setting the `KBRB5_CONFIG` environment variable.

**Comment by nalui333** [comment]
the client is windows so i'm hunting around trying to find how that is configured

**Comment by jcrist** [comment]
I have no windows + kerberos experience, so I'm not sure I'll be much help debugging here (sorry). The important thing is that your browser knows where the kerberos stuff (tickets, configuration, daemon address, etc...) is.

If you figure this out, I'd welcome any additions to the docs to help out future users.

**Comment by nalui333** [comment]
i'll definitely come back with info if/once i figure it out. thanks

**Comment by nalui333** [comment]
Hi I got the windows env to work with spnego but it was an AD issue. the problem i'm having now i's the authenticator is coming back with a "key table entry not found for http/@" even though i've specified the keytab file path  in the jupyter_config.py file. Is there some other config i should be changing? Thanks

**Comment by nalui333** [comment]
I was able to get everything to work right. it was a matter of getting the right service accound and and matching service principal name setup in AD and configuring the service.name and keytab variables in the jupyter_config.py file. Thanks for all your help. Your module rocks

**Comment by jcrist** [comment]
Great! Would you be willing to document the details of what was needed for AD support, either in a PR, or a comment here?
