### ISSUE TITLE
Support for creating system users

### ISSUE THREAD

**Issue by dvalters** [jupyterhub/kerberosauthenticator#5]
Hi, we'd like to add support to the kerberos authenticator for creating system users. (The option `create_system_users = True` in other authenticator plugins. )

A similar issue is described here, https://github.com/jupyterhub/jupyterhub/issues/932#issuecomment-271911940

And we have a patch implementing this that we could open as a PR, if you are open to contributions. (it would be nearly identical to this addition to the LDAPAuthenticator plugin, but for this kerberos plugin: see: https://github.com/jupyterhub/ldapauthenticator/pull/36)

**Comment by jcrist** [comment]
Sure, happy to accept a PR.

**Comment by jcrist** [comment]
Just released `kerberosauthenticator` version `0.2.0` to PyPI, which has these changes.
